### ISSUE TITLE
Bug Fixes: Force user to choose integers within the boundaries

### ISSUE THREAD

**Issue by williamye51** [williamye51/Guess-The-Number#5]
The program should not allow the user to enter an integer outside the boundaries and waste an attempt. Prompt the user with an error message about providing an integer within the boundary and continue the game.

**Comment by corey-new** [comment]
Hey @williamye51, I submitted a pull request to solve this issue. Let me know what you think! :)

**Comment by williamye51** [comment]
#8 closes this issue.
